#!/bin/sh

echo 'console.log("test")' >> app1/src/index.js
git commit -am 'update'
time (docker build -t app1 -f app1/Dockerfile app1 && \
      docker build -t app2 -f app2/Dockerfile app2 && \
      docker build -t app3 -f app3/Dockerfile app3 && \
      docker build -t app4 -f app4/Dockerfile app4 && \
      docker build -t app5 -f app5/Dockerfile app5)

echo 'console.log("test")' >> app1/src/index.js
git commit -am 'update'
time dapp dimg build
